name = "gander-social-translation-tool"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
FRONTEND_URL = "https://melodylumen.github.io"
JWT_SECRET = "${JWT_SECRET}"

# KV namespace for session storage
[[kv_namespaces]]
binding = "KV_BINDING"
id = "077b9a43f68c49a986cecae95ebf5f41"
preview_id = "077b9a43f68c49a986cecae95ebf5f41" # Use same ID for local dev

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "gander_social_translation_tool"
database_id = "65d4272a-e117-4737-a94b-b7d92f1e96a2"

# Durable Objects for WebSocket handling
[durable_objects]
bindings = [
    { name = "TRANSLATION_ROOMS", class_name = "TranslationRoom", script_name = "gander-social-translation-tool" }
]

# Routes
[[routes]]
pattern = "gander-social-translation-tool.melody-rae-lumen.workers.dev/*"
script = "gander-social-translation-tool"

[[routes]]
pattern = "gander-social-translation-tool.melody-rae-lumen.workers.dev/proxy/*"
script = "proxy"

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Build configuration
[build]
command = "npm install"

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["TranslationRoom"]