name: Deploy to Cloudflare
on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'wrangler.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run test
      - name: Deploy to Cloudflare
        run: npx wrangler deploy --yes
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
